---
- git:
    repo: git@github.com:FunTimeCoding/php-skeleton.git
    dest: '{{ ansible_user_dir }}/src/php-skeleton'
    version: '{{ php_skeleton.version }}'
  register: check_repository
  when: git.protocol == 'ssh'

- git:
    repo: https://github.com/FunTimeCoding/php-skeleton.git
    dest: '{{ ansible_user_dir }}/src/php-skeleton'
    version: '{{ php_skeleton.version }}'
  register: check_repository
  when: git.protocol == 'https'

- file:
    path: '{{ ansible_user_dir }}/src/php-skeleton/tmp'
    state: directory

- template:
    src: ethernet-device.txt
    dest: '{{ ansible_user_dir }}/src/php-skeleton/tmp/ethernet-device.txt'
    mode: 0644

- template:
    src: domain.txt
    dest: '{{ ansible_user_dir }}/src/php-skeleton/tmp/domain.txt'
    mode: 0644

- composer:
    command: install
    working_dir: '{{ ansible_user_dir }}/src/php-skeleton'
    executable: '{{ php_skeleton.php_executable }}'
  when: ansible_distribution_release != 'stretch'

- get_url:
    url: 'https://getcomposer.org/download/{{ composer.version }}/composer.phar'
    dest: '{{ ansible_user_dir }}/src/php-skeleton/composer.phar'
  when: ansible_distribution_release == 'stretch'

- stat:
    path: '{{ ansible_user_dir }}/src/php-skeleton/vendor'
  register: check_directory
  when: ansible_distribution_release == 'stretch'

- shell: '{{ php_skeleton.php_executable }} composer.phar install --no-progress'
  args:
    chdir: '{{ ansible_user_dir }}/src/php-skeleton'
  when: ansible_distribution_release == 'stretch' and (not check_directory.stat.exists or check_repository.changed)
